# Generated by Django 4.1 on 2022-08-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                ("direccion_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "direccion_calle",
                    models.CharField(max_length=255, verbose_name="Calle"),
                ),
                ("direccion_numero", models.IntegerField(verbose_name="Numero")),
                (
                    "direccion_ciudad",
                    models.CharField(max_length=255, verbose_name="Ciudad"),
                ),
                (
                    "direccion_provincia",
                    models.CharField(max_length=255, verbose_name="Provincia"),
                ),
                (
                    "direccion_pais",
                    models.CharField(max_length=255, verbose_name="Pais"),
                ),
            ],
            options={
                "verbose_name": "Direccion",
                "verbose_name_plural": "Direcciones",
                "db_table": "direccion",
                "ordering": ["-direccion_id"],
            },
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                ("branch_id", models.AutoField(primary_key=True, serialize=False)),
                ("branch_number", models.BinaryField()),
                ("branch_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Sucursal",
                "verbose_name_plural": "Sucursales",
                "db_table": "sucursal",
                "ordering": ["-branch_id"],
            },
        ),
        migrations.CreateModel(
            name="TipoCliente",
            fields=[
                (
                    "tipo_cliente_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("tipo_nombre", models.CharField(max_length=255, unique=True)),
                ("tipo_tarjeta_debito", models.CharField(max_length=255)),
                ("tipo_tarjeta_cretido", models.CharField(max_length=255)),
                ("tipo_cuenta_corriente", models.CharField(max_length=255)),
                ("tipo_chequera", models.IntegerField()),
                (
                    "tipo_cuenta_dolar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_cuenta_peso",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "retiro_diario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comision_transferencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recepcion", models.CharField(blank=True, max_length=255, null=True)),
                ("monto_pre_aprobado", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tipo cliente",
                "verbose_name_plural": "Tipo clientes",
                "db_table": "tipo cliente",
                "ordering": ["-tipo_cliente_id"],
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("empleado_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "empleado_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "empleado_apellido",
                    models.CharField(max_length=255, verbose_name="Apellido"),
                ),
                (
                    "empleado_dni",
                    models.IntegerField(db_column="empleado_dni", verbose_name="DNI"),
                ),
                (
                    "empleado_fecha_contratacion",
                    models.CharField(
                        max_length=255, verbose_name="Fecha de contratacion"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "empleado_direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.direccion",
                        verbose_name="Direccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "db_table": "empleado",
                "ordering": ["-empleado_id"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cliente_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cliente_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "cliente_apellido",
                    models.CharField(max_length=255, verbose_name="Apellido"),
                ),
                ("cliente_dni", models.IntegerField(verbose_name="DNI")),
                (
                    "cliente_dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "cliente_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "cliente_telefono",
                    models.IntegerField(blank=True, null=True, verbose_name="Telefono"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.sucursal",
                        verbose_name="Sucursal",
                    ),
                ),
                (
                    "cliente_direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.direccion",
                        verbose_name="Direccion",
                    ),
                ),
                (
                    "cliente_tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.tipocliente",
                        verbose_name="Tipo cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Cliente",
                "ordering": ["-cliente_id"],
            },
        ),
    ]
