# Generated by Django 4.1 on 2022-08-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("direccion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cliente_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cliente_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre"),
                ),
                (
                    "cliente_apellido",
                    models.CharField(max_length=255, verbose_name="Apellido"),
                ),
                ("cliente_dni", models.IntegerField(verbose_name="DNI")),
                (
                    "cliente_dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "cliente_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "cliente_telefono",
                    models.IntegerField(blank=True, null=True, verbose_name="Telefono"),
                ),
                (
                    "cliente_direccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="direccion.direccion",
                        verbose_name="Direccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "Cliente",
                "ordering": ["-cliente_id"],
            },
        ),
    ]
