# Generated by Django 4.1 on 2022-08-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0002_alter_cliente_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="cliente_direccion",
        ),
    ]
