# Generated by Django 4.1 on 2022-08-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sucursal", "0001_initial"),
        ("cliente", "0005_cliente_cliente_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sucursal.sucursal",
                verbose_name="Sucursal",
            ),
        ),
    ]
