# Generated by Django 4.1 on 2022-09-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TipoCliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipocliente",
            options={
                "verbose_name": "Tipo cliente",
                "verbose_name_plural": "Tipo clientes",
            },
        ),
        migrations.RenameField(
            model_name="tipocliente",
            old_name="comision_transferencia",
            new_name="tipo_comision_transferencia",
        ),
        migrations.RenameField(
            model_name="tipocliente",
            old_name="monto_pre_aprobado",
            new_name="tipo_monto_pre_aprobado",
        ),
        migrations.RenameField(
            model_name="tipocliente",
            old_name="recepcion",
            new_name="tipo_recepcion",
        ),
        migrations.RenameField(
            model_name="tipocliente",
            old_name="retiro_diario",
            new_name="tipo_retiro_diario",
        ),
    ]
