# Generated by Django 4.1 on 2022-09-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TipoCliente", "0002_alter_tipocliente_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipocliente",
            name="tipo_nombre",
        ),
        migrations.AddField(
            model_name="tipocliente",
            name="ipo_cliente",
            field=models.CharField(
                choices=[("Classic", "Classic"), ("Gold", "Gold"), ("Black", "Black")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
