# Generated by Django 4.1 on 2022-08-31 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0006_cliente_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="TarjetaMarca",
            fields=[
                ("marca_id", models.AutoField(primary_key=True, serialize=False)),
                ("marca_nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Marca Tarjeta",
                "verbose_name_plural": "Marcas Tarjetas",
                "db_table": "marca_tarjeta",
            },
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                ("tarjeta_id", models.AutoField(primary_key=True, serialize=False)),
                ("tarjeta_numero", models.CharField(max_length=200, unique=True)),
                ("tarjeta_cvv", models.IntegerField()),
                ("tarjeta_emision", models.CharField(max_length=255)),
                ("tarjeta_expiracion", models.CharField(max_length=255)),
                ("tarjeta_tipo", models.CharField(max_length=255)),
                (
                    "tarjeta_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "tarjeta_marca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tarjeta.tarjetamarca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta",
                "verbose_name_plural": "Tarjetas",
                "db_table": "tarjeta",
            },
        ),
    ]
