# Generated by Django 4.1 on 2022-09-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0002_alter_tarjetamarca_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarjeta",
            name="tarjeta_marca",
        ),
    ]
