# Generated by Django 4.1 on 2022-09-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0003_remove_tarjeta_tarjeta_marca"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TarjetaMarca",
        ),
    ]
