# Generated by Django 4.1 on 2022-09-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0004_delete_tarjetamarca"),
    ]

    operations = [
        migrations.CreateModel(
            name="TarjetaMarca",
            fields=[
                ("marca_id", models.AutoField(primary_key=True, serialize=False)),
                ("marca_nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tarjeta Marca",
                "verbose_name_plural": "Tarjeta Marcas",
                "db_table": "TarjetaMarca",
            },
        ),
        migrations.AddField(
            model_name="tarjeta",
            name="tarjeta_marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tarjeta.tarjetamarca",
            ),
        ),
    ]
