# Generated by Django 4.1 on 2022-09-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0005_tarjetamarca_tarjeta_tarjeta_marca"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarjeta",
            name="tarjeta_marca",
        ),
        migrations.RemoveField(
            model_name="tarjeta",
            name="tarjeta_tipo",
        ),
        migrations.AddField(
            model_name="tarjeta",
            name="marca",
            field=models.CharField(
                choices=[("V", "VISA"), ("M", "MASTERCARD")], default=1, max_length=2
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tarjeta",
            name="tipo",
            field=models.CharField(
                choices=[("C", "CREDITO"), ("D", "DEBITO")], default=1, max_length=2
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TarjetaMarca",
        ),
    ]
