# Generated by Django 4.1 on 2022-09-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0006_remove_tarjeta_tarjeta_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="marca",
            field=models.CharField(
                choices=[("V", "VISA"), ("M", "MASTERCARD")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="tarjeta",
            name="tipo",
            field=models.CharField(
                choices=[("C", "CREDITO"), ("D", "DEBITO")], max_length=10
            ),
        ),
    ]
