# Generated by Django 4.1 on 2022-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0007_alter_tarjeta_marca_alter_tarjeta_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="marca",
            field=models.CharField(
                choices=[("VISA", "VISA"), ("MASTERCARD", "MASTERCARD")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="tarjeta",
            name="tipo",
            field=models.CharField(
                choices=[("CREDITO", "CREDITO"), ("DEBITO", "DEBITO")], max_length=10
            ),
        ),
    ]
