# Generated by Django 4.1 on 2022-09-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarjeta", "0009_rename_marca_tarjeta_tarjeta_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="tarjeta_numero",
            field=models.CharField(max_length=200),
        ),
    ]
