# Generated by Django 4.1 on 2022-09-02 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sucursal", "0002_alter_sucursal_branch_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sucursal",
            options={"verbose_name": "Sucursal", "verbose_name_plural": "Sucursales"},
        ),
    ]
