# Generated by Django 4.1 on 2022-08-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cliente", "0006_cliente_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoCuenta",
            fields=[
                ("tipo_cuenta_id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_cuenta_nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de cuenta",
                "verbose_name_plural": "Tipo de cuentas",
                "db_table": "tipo_cuenta",
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                ("cuenta_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuenta_balance", models.IntegerField()),
                ("cuenta_iban", models.CharField(max_length=255)),
                (
                    "cuenta_cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cliente.cliente",
                    ),
                ),
                (
                    "cuenta_tipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cuenta.tipocuenta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta",
                "verbose_name_plural": "Cuentas",
                "db_table": "cuenta",
            },
        ),
    ]
