# Generated by Django 4.1 on 2022-09-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuenta", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuenta",
            name="cuenta_tipo",
        ),
        migrations.AddField(
            model_name="cuenta",
            name="tipo_cuenta",
            field=models.CharField(
                choices=[
                    ("CAJA DE AHORRO EN PESOS", "CAJA DE AHORRO EN PESOS"),
                    ("CAJA DE AHORRO EN DOLARES", "CAJA DE AHORRO EN DOLARES"),
                    ("CUENTA CORRIENTE", "CUENTA CORRIENTE"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
