# Generated by Django 4.1 on 2022-09-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestamo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("HIPOTECARIO", "HIPOTECARIO"),
                    ("PRENDARIO", "PRENDARIO"),
                    ("PERSONAL", "PERSONAL"),
                ],
                default=1,
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TipoPrestamo",
        ),
    ]
