# Generated by Django 4.1 on 2022-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                ("direccion_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "direccion_calle",
                    models.CharField(max_length=255, verbose_name="Calle"),
                ),
                ("direccion_numero", models.IntegerField(verbose_name="Numero")),
                (
                    "direccion_ciudad",
                    models.CharField(max_length=255, verbose_name="Ciudad"),
                ),
                (
                    "direccion_provincia",
                    models.CharField(max_length=255, verbose_name="Provincia"),
                ),
                (
                    "direccion_pais",
                    models.CharField(max_length=255, verbose_name="Pais"),
                ),
            ],
            options={
                "verbose_name": "Direccion",
                "verbose_name_plural": "Direcciones",
                "db_table": "direccion",
                "ordering": ["-direccion_id"],
            },
        ),
    ]
