# Generated by Django 4.1 on 2022-08-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("direccion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direccion",
            options={"verbose_name": "Direccion", "verbose_name_plural": "Direcciones"},
        ),
    ]
